### ISSUE TITLE
[common] Archive.org broken ($15 bounty - backed)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#10]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28378995)](https://www.bountysource.com/issues/28378995-common-archive-org-broken?utm_source=28378995&utm_medium=shield&utm_campaign=ISSUE_BADGE)

This should be as simple as taking a look at changes in the JSON output of the Archive.org API and updating our respective objects to match whatever they have changed.

If it's any more complex it could be only because they've changed the REST URL structures and then it's a matter of changing URLs.

```
FrostWire version 6.1.7 build 168
Nov 18, 2015 2:45:50 PM com.frostwire.search.PagedWebSearchPerformer 
INFO: Error searching page: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.frostwire.util.JsonUtils.toObject(Unknown Source)
at com.frostwire.search.archiveorg.ArchiveorgSearchPerformer.searchPage(Unknown Source)
at com.frostwire.search.PagedWebSearchPerformer.searchPage(Unknown Source)
at com.frostwire.search.PagedWebSearchPerformer.perform(Unknown Source)
at com.frostwire.search.SearchManagerImpl$PerformTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
at com.google.gson.stream.JsonReader.beginArray(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
... 20 more
```

Perhaps @votaguz or @X-NicON  might want to take a look?

Starting point to look is `at com.frostwire.search.archiveorg.ArchiveorgSearchPerformer.searchPage` and its related classes.

**Comment by X-NicON** [comment]
I coped.
however, the entire response was written in error ...

**Comment by gubatron** [comment]
have fun!

**Comment by gubatron** [comment]
does it work now? or still work in progress? [WIP]

**Comment by gubatron** [comment]
I've tested this and it works now. Merging and releasing bounty. Thank you!

**Comment by gubatron** [comment]
Bounty released, thank you very much.
<img width="592" alt="screen shot 2015-11-20 at 6 39 17 am" src="https://cloud.githubusercontent.com/assets/163977/11299060/7a4bc188-8f51-11e5-951a-9da26a12e420.png">
