### ISSUE TITLE
[desktop] macOS version not getting update message

### ISSUE THREAD

**Issue by Paulinka** [frostwire/frostwire#1000]
console log throws this, good luck
```
UpdateMessageReader.readUpdateFile() java.lang.NullPointerException java.lang.NullPointerException: Cannot invoke "com.frostwire.gui.updates.UpdateMessage.getOs()" because "this._bufferMessage" is null
java.lang.NullPointerException: Cannot invoke "com.frostwire.gui.updates.UpdateMessage.getOs()" because "this._bufferMessage" is null
	at com.frostwire.gui.updates.UpdateMessageReader.endElement(UpdateMessageReader.java:125)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2899)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at com.frostwire.gui.updates.UpdateMessageReader.readUpdateFile(UpdateMessageReader.java:295)
	at com.frostwire.gui.updates.UpdateManager.checkForUpdates(UpdateManager.java:230)
	at com.frostwire.gui.updates.UpdateManager.lambda$scheduleUpdateCheckTask$0(UpdateManager.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
InstallerUpdater.checkIfDownloaded() - File <frostwire-6.9.10-x86_64.dmg> does not exist
Jan 25, 2023 2:34:38 PM UpdateManager 
INFO: checkForUpdates() has no announcements
javax.net.ssl.SSLPeerUnverifiedException: Hostname github.com not verified:
    certificate: sha256//3ftdeWqIAONye/CeEQuLGvtlw4MPnQmKgyPLugFbK8=
    DN: CN=github.com, O="GitHub, Inc.", L=San Francisco, ST=California, C=US
    subjectAltNames: [github.com, www.github.com]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:389)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.frostwire.util.http.OkHttpClientWrapper.getSyncResponse(OkHttpClientWrapper.java:330)
	at com.frostwire.util.http.OkHttpClientWrapper.save(OkHttpClientWrapper.java:196)
	at com.frostwire.util.http.AbstractHttpClient.save(AbstractHttpClient.java:174)
	at com.frostwire.util.http.AbstractHttpClient.save(AbstractHttpClient.java:169)
	at com.frostwire.gui.updates.InstallerUpdater.handleHttpDownload(InstallerUpdater.java:213)
	at com.frostwire.gui.updates.InstallerUpdater.run(InstallerUpdater.java:142)
	at java.base/java.lang.Thread.run(Thread.java:833)
InstallerUpdater.downloadComplete()!!!!
InstallerUpdater.cleanupInvalidUpdates() -> removed frostwire-6.9.10-x86_64.dmg (file size: 0 bytes)
InstallerUpdater.cleanupInvalidUpdates() -> downloaded from https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.9.10-build-315/frostwire-6.9.10-x86_64.dmg
InstallerUpdater.cleanupInvalidUpdates() -> expected MD5=c2d33d5d512fa12480fc43adb8c69112 vs frostwire-6.9.10-x86_64.dmg MD5=d41d8cd98f00b204e9800998ecf8427e

```

**Comment by gubatron** [comment]
theory, that version of frostwire doesn't know how to parse the arm message, and by default tries to get the x86 installer.

However, perhaps there's an issue with the certificate and the download logic.

**Comment by gubatron** [comment]
that was frostwire 6.9.7 build 311

**Comment by gubatron** [comment]
that's the first build with arm support for mac.
Will test with that.
