### ISSUE TITLE
[android] crash on SearchManager.perform (line 76)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#110]
Appeared on beta roll out for 1.7.2, must be something related to latest changes on search framework.

```
java.lang.IllegalArgumentException: Search performer argument can't be null
	at com.frostwire.search.SearchManager.perform(SearchManager.java:76)
	at com.frostwire.android.gui.LocalSearchEngine.performSearch(LocalSearchEngine.java:108)
	at com.frostwire.android.gui.fragments.SearchFragment.performSearch(SearchFragment.java:326)
	at com.frostwire.android.gui.fragments.SearchFragment.access$500(SearchFragment.java:80)
	at com.frostwire.android.gui.fragments.SearchFragment$1.onSearch(SearchFragment.java:184)
	at com.frostwire.android.gui.views.SearchInputView.onSearch(SearchInputView.java:155)
	at com.frostwire.android.gui.views.SearchInputView.startSearch(SearchInputView.java:147)
	at com.frostwire.android.gui.views.SearchInputView.access$000(SearchInputView.java:43)
	at com.frostwire.android.gui.views.SearchInputView$TextInputClickListener.onKey(SearchInputView.java:278)
	at com.frostwire.android.gui.views.SearchInputView$TextInputClickListener.onKey(SearchInputView.java:269)
	at com.frostwire.android.gui.views.ClickAdapter.onKey(ClickAdapter.java:60)
	at android.view.View.dispatchKeyEvent(View.java:7751)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1419)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2183)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1553)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2512)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2110)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4119)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5925)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5874)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5845)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3438)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire/commit/de95b4484ff0535bf728ec03f7679a91a0877c8e
