### ISSUE TITLE
[android/crash] Possible crash on Exit.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#153]
```
--------- beginning of crash
06-02 15:13:12.389 12967-12967/com.frostwire.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.frostwire.android, PID: 12967
                                                                       java.lang.RuntimeException: Unable to stop service com.frostwire.android.gui.services.EngineService@45d9c95: java.lang.IllegalArgumentException: Service not registered: com.android.vending.billing.IabHelper$1@1d0344c
                                                                           at android.app.ActivityThread.handleStopService(ActivityThread.java:3059)
                                                                           at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1447)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.lang.IllegalArgumentException: Service not registered: com.android.vending.billing.IabHelper$1@1d0344c
                                                                           at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
                                                                           at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
                                                                           at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
                                                                           at com.android.vending.billing.IabHelper.dispose(IabHelper.java:328)
                                                                           at com.android.vending.billing.IabHelper.disposeWhenFinished(IabHelper.java:348)
                                                                           at com.frostwire.android.offers.PlayStore.dispose(PlayStore.java:153)
                                                                           at com.frostwire.android.gui.services.EngineService.onDestroy(EngineService.java:119)
                                                                           at android.app.ActivityThread.handleStopService(ActivityThread.java:3040)
                                                                           at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1447) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
06-02 15:16:41.620 12967-12967/com.frostwire.android I/Process: Sending signal. PID: 12967 SIG: 9
```

**Comment by gubatron** [comment]
maybe this also helps, this is what happens when the app starts:
```
06-02 15:28:56.390 16958-16958/com.frostwire.android E/com.frostwire.android.offers.PlayStore: In-app billing error: Illegal state for operation (queryInventory): IAB helper is not set up.
06-02 15:28:56.390 16958-16958/com.frostwire.android I/EngineBroadcastReceiver: Error processing broadcast message
                                                                                java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: queryInventory
                                                                                    at com.android.vending.billing.IabHelper.checkSetupDone(IabHelper.java:859)
                                                                                    at com.android.vending.billing.IabHelper.queryInventoryAsync(IabHelper.java:689)
                                                                                    at com.android.vending.billing.IabHelper.queryInventoryAsync(IabHelper.java:719)
                                                                                    at com.frostwire.android.offers.PlayStore.refresh(PlayStore.java:141)
                                                                                    at com.frostwire.android.gui.services.EngineBroadcastReceiver.handleConnectedNetwork(EngineBroadcastReceiver.java:120)
                                                                                    at com.frostwire.android.gui.services.EngineBroadcastReceiver.onReceive(EngineBroadcastReceiver.java:84)
                                                                                    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by aldenml** [comment]
This log is normal, it's precisely that you don't have google services in the emulator

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire/commit/0839250d542adc5aba286b7481f81da702688655

**Comment by gubatron** [comment]
Thank you
