### ISSUE TITLE
[desktop] NPE at com.frostwire.gui.bittorrent.BTDownloadMediator.doRefresh

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#160]
6.3.1 build 186

```
java.lang.NullPointerException
        at com.frostwire.gui.bittorrent.BTDownloadMediator.doRefresh(Unknown Source)
        at com.limegroup.gnutella.gui.tables.AbstractTableMediator.refresh(Unknown Source)
        at com.limegroup.gnutella.gui.GUIMediator.refreshGUI(Unknown Source)
        at com.limegroup.gnutella.gui.RefreshTimer.refreshGUI(Unknown Source)
        at com.limegroup.gnutella.gui.RefreshTimer.access$000(Unknown Source)
        at com.limegroup.gnutella.gui.RefreshTimer$1.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by gubatron** [comment]
[This](https://github.com/frostwire/frostwire/commit/c0a8904600832b0428470b0d87fde3e94497cc02) should avoid any crashes from happening on this `doRefresh()` method.

However, this does not find the cause of what could be `null` here.

My guess is that it has something to do with the new transfer view when it's by itself.
