### ISSUE TITLE
[android] Handle this exception for very demanding users

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#161]
It seems some people have, or think that they have an Intel Xeon running on those HTC Desires, he he. This user had the threadpool fully occupied and the app crashed when he tried to submit another task.

Perhaps we should have a simple message to please wait until some of the downloads finished, system at maximum capacity.

```
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@36526c98 rejected from java.util.concurrent.ThreadPoolExecutor@2c76d226[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 531]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:594)
	at com.frostwire.android.gui.tasks.Tasks.execute(Tasks.java:59)
	at com.frostwire.android.gui.tasks.Tasks.executeParallel(Tasks.java:43)
	at com.frostwire.android.gui.fragments.SearchFragment.startDownload(SearchFragment.java:375)
	at com.frostwire.android.gui.fragments.SearchFragment.startTransfer(SearchFragment.java:364)
	at com.frostwire.android.gui.fragments.SearchFragment.access$600(SearchFragment.java:80)
	at com.frostwire.android.gui.fragments.SearchFragment$3.searchResultClicked(SearchFragment.java:222)
	at com.frostwire.android.gui.adapters.SearchResultListAdapter.onItemClicked(SearchResultListAdapter.java:184)
	at com.frostwire.android.gui.views.AbstractListAdapter$ViewOnClickListener.onClick(AbstractListAdapter.java:532)
	at android.view.View.performClick(View.java:4806)
	at android.view.View$PerformClick.run(View.java:19983)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5725)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Comment by aldenml** [comment]
One more reason to move away of `android.os.AsyncTask`, but still we need to review why this could happen

**Comment by gubatron** [comment]
now that I read about it, we're using this AsyncTask in the worst place possible as a download is a long lived operation, and the documentation of AsyncTask actually recommends otherwise.

```
AsyncTasks should ideally be used for short operations (a few seconds at the most.) 
```

However as I see the code, I see that many of the transfers extend from `ContextTask`, as they need a context to work with. What should be the way to go? Refactoring into Runnables, putting them on the Executors we already have and using Handler/Post ?

**Comment by aldenml** [comment]
I rather say `AsyncTasks` should not be used at all :)

Yes, the refactor is the way to go, however, I think we should have to pools, one for UI background tasks fine tuned for that, and another for other tasks (in the same way we have a pool for search and another for http).
