### ISSUE TITLE
[android] java.lang.IllegalArgumentException: Can't decode data from file (file not found)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#162]
```
java.lang.IllegalArgumentException: Can't decode data from file: /storage/emulated/0/FrostWire/Torrents/foobar.torrent
at com.frostwire.jlibtorrent.TorrentInfo.bdecode0(TorrentInfo.java:642)
	at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:33)
	at com.frostwire.bittorrent.BTEngine.download(BTEngine.java:347)
	at com.frostwire.android.gui.adapters.menu.SeedAction.seedFileDescriptor(SeedAction.java:199)
	at com.frostwire.android.gui.adapters.menu.SeedAction.seedFileDescriptors(SeedAction.java:207)
	at com.frostwire.android.gui.adapters.menu.SeedAction.seedEm(SeedAction.java:187)
	at com.frostwire.android.gui.adapters.menu.SeedAction.onClick(SeedAction.java:131)
	at com.frostwire.android.gui.views.MenuAction.onClick(MenuAction.java:66)
	at com.frostwire.android.gui.views.MenuBuilder.onClick(MenuBuilder.java:46)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1165)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1189)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3114)
	at android.widget.AbsListView$3.run(AbsListView.java:4079)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by: java.io.FileNotFoundException: File '/storage/emulated/0/FrostWire/Torrents/foobar.torrent' does not exist
	at com.frostwire.jlibtorrent.Files.openInputStream(Files.java:75)
	at com.frostwire.jlibtorrent.Files.bytes(Files.java:41)
	at com.frostwire.jlibtorrent.TorrentInfo.bdecode0(TorrentInfo.java:639)
	... 21 more
```

**Comment by aldenml** [comment]
What's the error?

**Comment by gubatron** [comment]
I think they might be trying to seed and they could be having issues with the SD card.

However, I remember that feature was supposed to be disabled for android's with sd card because the torrent creation wasn't compatible yet with the way we're supposed to access files.

In any case, if the file cannot be found for X reason, we should just display an error message and not crash.
