### ISSUE TITLE
[desktop/windows] music playback broken

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#187]
(probably only for the development environment)

```
java.io.IOException: Cannot run program "C:\Users\mucka_000\frostwire\desktop\..\lib\native\fwplayer.exe": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.frostwire.gui.mplayer.MPlayerInstance.doOpen(MPlayerInstance.java:313)
        at com.frostwire.gui.mplayer.MPlayer.doOpen(MPlayer.java:513)
        at com.frostwire.mplayer.BaseMediaPlayer.open(BaseMediaPlayer.java:156)
        at com.frostwire.gui.player.MediaPlayer.playMedia(MediaPlayer.java:379)
        at com.frostwire.gui.player.MediaPlayer.loadMedia(MediaPlayer.java:249)
        at com.frostwire.gui.player.MediaPlayer$5.run(MediaPlayer.java:307)
        at org.limewire.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1010)
        at org.limewire.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:553)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 10 more
```

**Comment by gubatron** [comment]
works fine in ubuntu... (happened to be in ubuntu)

**Comment by muckachina** [comment]
Perfect! Tested on Windows and Mac and is Ok, initial issue solved and now Player working fine again on Windows :)

Thanks!
