### ISSUE TITLE
[android/crash] crash on shutdown (probably the finishActivityAffinity)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#190]
```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.am.TaskRecord com.android.server.am.ActivityRecord.task' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1552)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.ActivityManagerProxy.finishActivityAffinity(ActivityManagerNative.java:2790)
	at android.app.Activity.finishAffinity(Activity.java:4752)
	at com.frostwire.android.gui.activities.MainActivity.shutdown(MainActivity.java:177)
	at com.frostwire.android.offers.Offers$AdNetworkHelper.dismissAndOrShutdownIfNecessary(Offers.java:280)
	at com.frostwire.android.offers.AppLovinInterstitialAdapter.adHidden(AppLovinInterstitialAdapter.java:119)
	at com.applovin.adview.AppLovinInterstitialActivity.c(Unknown Source)
	at com.applovin.adview.AppLovinInterstitialActivity.dismiss(Unknown Source)
	at com.applovin.adview.q.onClick(Unknown Source)
```

**Comment by aldenml** [comment]
You removed the class to `finishAffinity` right?

**Comment by aldenml** [comment]
no, it's still there

**Comment by gubatron** [comment]
just did

**Comment by gpandroid90** [comment]
we are getting the same issue what is the solution for this?

**Comment by vidhi5** [comment]
Facing the same issue

**Comment by gubatron** [comment]
@vidhi5 what build number are you on?
