### ISSUE TITLE
[desktop/resources] tzdb.dat missing in JRE

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#195]
```
java.lang.Error: java.io.FileNotFoundException: C:\Users\Fotos y canciones\Downloads\FrostWire 6\jre\lib\tzdb.dat (The system cannot find the file specified)
        at sun.util.calendar.ZoneInfoFile$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.util.calendar.ZoneInfoFile.<clinit>(Unknown Source)
        at sun.util.calendar.ZoneInfo.getTimeZone(Unknown Source)
        at java.util.TimeZone.getTimeZone(Unknown Source)
        at java.util.TimeZone.setDefaultZone(Unknown Source)
        at java.util.TimeZone.getDefaultRef(Unknown Source)
        at java.util.TimeZone.getDefault(Unknown Source)
        at java.text.SimpleDateFormat.initializeCalendar(Unknown Source)
        at java.text.SimpleDateFormat.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.GUIUtils.resetLocale(Unknown Source)
        at com.limegroup.gnutella.gui.GUIUtils.<clinit>(Unknown Source)
        at com.limegroup.gnutella.gui.StatusComponent.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.SplashWindow.initialize(Unknown Source)
        at com.limegroup.gnutella.gui.SplashWindow.access$100(Unknown Source)
        at com.limegroup.gnutella.gui.SplashWindow$2.run(Unknown Source)
        at com.limegroup.gnutella.gui.GUIMediator.safeInvokeAndWait(Unknown Source)
        at com.limegroup.gnutella.gui.SplashWindow.runLater(Unknown Source)
        at com.limegroup.gnutella.gui.SplashWindow.begin(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer$2.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by aldenml** [comment]
The file is there, but he obviously installed the app in a strange place to start with.

**Comment by gubatron** [comment]
So I was wondering if that was the case, when I saw the install location, but then I checked my own installation and I didn't see the file either on my system, I'll double check.

We need to put some validation on the installer to avoid installing on the save folder

**Comment by aldenml** [comment]
If it's not in your system, that's a problem, because it should, it's in both JRE for macOS and Windows

**Comment by gubatron** [comment]
nvm, got it - 102kb, phew
