### ISSUE TITLE
[desktop] Create a Playlist - Files are not being imported to the Playlist

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#2]
OS: **Mac OS 10.10, Windows XP, 10 and 8**
**FrostWire version 6.1.6 (build 167)
Screen: **Library** 
Test: **Create a new Playlist**
**Ref. L-Play-1**

**Observations:** 

**On Windows**:
- When dragging and dropping files to create a playlist from scratch the files are not being placed on the Playlist.

- If I drag and drop files to an existing Playlist then the entire list of files just disappears.

**On Mac**:
- If I drag and drop files to an existing Playlist then the entire list of files just disappears.

- When dragging and dropping files to create a playlist from scratch **the app freezes and I cannot close, cancel or exit the "Playlist name creation"**

Here the log:
*Ninja - Slow Mournings - Free FrostWire Mixtape.mp3]
Nov 09, 2015 8:12:52 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 05 Shinobi Ninja - Slow Mournings - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:12:52 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 05 Shinobi Ninja - Slow Mournings - Free FrostWire Mixtape.mp3:Invalid Frame:05 Shinobi Ninja - Slow Mournings - Free FrostWire Mixtape.mp3:No space to find another frame
-> get_property LENGTH
-> get_property SUB
-> get_property ASPECT
-> get_property WIDTH
-> get_property HEIGHT
-> get_property VOLUME
-> pause
Nov 09, 2015 8:12:57 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:12:57 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:Invalid Frame:03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame
Nov 09, 2015 8:13:00 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:13:00 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:Invalid Frame:03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame
org.h2.jdbc.JdbcSQLException: Error creating or initializing trigger "FTL_PLAYLISTITEMS" object, class "org.h2.fulltext.FullTextLucene2$FullTextTrigger", cause: "org.h2.message.DbException: Class ""org.h2.fulltext.FullTextLucene2$FullTextTrigger"" not found [90086-186]"; see root cause for details [90043-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.schema.TriggerObject.load(Unknown Source)
	at org.h2.schema.TriggerObject.fireRow(Unknown Source)
	at org.h2.table.Table.fireRow(Unknown Source)
	at org.h2.table.Table.fireAfterRow(Unknown Source)
	at org.h2.engine.UndoLogRecord.undo(Unknown Source)
	at org.h2.engine.Session.rollbackTo(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.insert(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistItemDB.save(Unknown Source)
	at com.frostwire.alexandria.PlaylistItem.save(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.addPlaylistItem(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.addToPlaylist(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.access$600(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils$8.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.message.DbException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.util.JdbcUtils.loadUserClass(Unknown Source)
	... 19 more
Caused by: org.h2.jdbc.JdbcSQLException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.h2.fulltext.FullTextLucene2$FullTextTrigger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	... 20 more
Nov 09, 2015 8:13:01 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:13:01 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:Invalid Frame:02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:No space to find another frame
org.h2.jdbc.JdbcSQLException: Error creating or initializing trigger "FTL_PLAYLISTITEMS" object, class "org.h2.fulltext.FullTextLucene2$FullTextTrigger", cause: "org.h2.message.DbException: Class ""org.h2.fulltext.FullTextLucene2$FullTextTrigger"" not found [90086-186]"; see root cause for details [90043-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.schema.TriggerObject.load(Unknown Source)
	at org.h2.schema.TriggerObject.fireRow(Unknown Source)
	at org.h2.table.Table.fireRow(Unknown Source)
	at org.h2.table.Table.fireAfterRow(Unknown Source)
	at org.h2.engine.UndoLogRecord.undo(Unknown Source)
	at org.h2.engine.Session.rollbackTo(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.insert(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistItemDB.save(Unknown Source)
	at com.frostwire.alexandria.PlaylistItem.save(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.addPlaylistItem(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.addToPlaylist(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils.access$600(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils$8.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.message.DbException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.util.JdbcUtils.loadUserClass(Unknown Source)
	... 19 more
Caused by: org.h2.jdbc.JdbcSQLException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.h2.fulltext.FullTextLucene2$FullTextTrigger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	... 20 more
org.h2.jdbc.JdbcSQLException: Error creating or initializing trigger "FTL_PLAYLISTITEMS" object, class "org.h2.fulltext.FullTextLucene2$FullTextTrigger", cause: "org.h2.message.DbException: Class ""org.h2.fulltext.FullTextLucene2$FullTextTrigger"" not found [90086-186]"; see root cause for details [90043-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.schema.TriggerObject.load(Unknown Source)
	at org.h2.schema.TriggerObject.fireRow(Unknown Source)
	at org.h2.table.Table.fireRow(Unknown Source)
	at org.h2.table.Table.fireAfterRow(Unknown Source)
	at org.h2.engine.UndoLogRecord.undo(Unknown Source)
	at org.h2.engine.Session.rollbackTo(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.insert(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistItemDB.save(Unknown Source)
	at com.frostwire.alexandria.PlaylistItem.save(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistDB.save(Unknown Source)
	at com.frostwire.alexandria.Playlist.save(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils$8.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.message.DbException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.util.JdbcUtils.loadUserClass(Unknown Source)
	... 18 more
Caused by: org.h2.jdbc.JdbcSQLException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.h2.fulltext.FullTextLucene2$FullTextTrigger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	... 19 more
org.h2.jdbc.JdbcSQLException: Error creating or initializing trigger "FTL_PLAYLISTITEMS" object, class "org.h2.fulltext.FullTextLucene2$FullTextTrigger", cause: "org.h2.message.DbException: Class ""org.h2.fulltext.FullTextLucene2$FullTextTrigger"" not found [90086-186]"; see root cause for details [90043-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.schema.TriggerObject.load(Unknown Source)
	at org.h2.schema.TriggerObject.fireRow(Unknown Source)
	at org.h2.table.Table.fireRow(Unknown Source)
	at org.h2.table.Table.fireAfterRow(Unknown Source)
	at org.h2.engine.UndoLogRecord.undo(Unknown Source)
	at org.h2.engine.Session.rollbackTo(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.update(Unknown Source)
	at com.frostwire.alexandria.db.LibraryDatabase.insert(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistItemDB.save(Unknown Source)
	at com.frostwire.alexandria.PlaylistItem.save(Unknown Source)
	at com.frostwire.alexandria.db.PlaylistDB.save(Unknown Source)
	at com.frostwire.alexandria.Playlist.save(Unknown Source)
	at com.frostwire.gui.library.LibraryUtils$8.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.message.DbException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.util.JdbcUtils.loadUserClass(Unknown Source)
	... 18 more
Caused by: org.h2.jdbc.JdbcSQLException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.h2.fulltext.FullTextLucene2$FullTextTrigger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	... 19 more
Nov 09, 2015 8:13:50 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:13:50 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:Invalid Frame:03 Shinobi Ninja - Gloom Doom - Free FrostWire Mixtape.mp3:No space to find another frame
Nov 09, 2015 8:13:50 PM org.jaudiotagger.tag.id3.AbstractID3v2Frame readIdentifier
WARNING: 02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:No space to find another frame:
Nov 09, 2015 8:13:50 PM org.jaudiotagger.tag.id3.ID3v23Tag readFrames
WARNING: 02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:Invalid Frame:02 Shinobi Ninja - What If Times - Free FrostWire Mixtape.mp3:No space to find another frame*

**Comment by gubatron** [comment]
Confirmed, tried deleting elements from playlist and it is that `FullTextLucene2$FullTextTrigger` class missing

```
 Class ""org.h2.fulltext.FullTextLucene2$FullTextTrigger"" not found [90086-186]"; see root cause for details [90043-186]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.schema.TriggerObject.load(TriggerObject.java:86)
	at org.h2.schema.TriggerObject.fireRow(TriggerObject.java:211)
	at org.h2.table.Table.fireRow(Table.java:946)
	at org.h2.table.Table.fireAfterRow(Table.java:936)
	at org.h2.engine.UndoLogRecord.undo(UndoLogRecord.java:111)
	at org.h2.engine.Session.rollbackTo(Session.java:599)
	at org.h2.command.Command.executeUpdate(Command.java:278)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
	at com.frostwire.alexandria.db.LibraryDatabase.update(LibraryDatabase.java:296)
	at com.frostwire.alexandria.db.LibraryDatabase.update(LibraryDatabase.java:82)
	at com.frostwire.alexandria.db.PlaylistItemDB.delete(PlaylistItemDB.java:83)
	at com.frostwire.alexandria.PlaylistItem.delete(PlaylistItem.java:202)
	at com.frostwire.gui.library.LibraryPlaylistsTableMediator.removeSelection(LibraryPlaylistsTableMediator.java:485)
	at com.limegroup.gnutella.gui.tables.RemoveListener.actionPerformed(RemoveListener.java:20)
	at com.frostwire.gui.library.LibraryPlaylistsTableMediator$RemoveFromPlaylistAction.actionPerformed(LibraryPlaylistsTableMediator.java:772)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.h2.message.DbException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:188)
	at org.h2.schema.TriggerObject.load(TriggerObject.java:76)
	... 54 more
Caused by: org.h2.jdbc.JdbcSQLException: Class "org.h2.fulltext.FullTextLucene2$FullTextTrigger" not found [90086-186]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 57 more
Caused by: java.lang.ClassNotFoundException: org.h2.fulltext.FullTextLucene2$FullTextTrigger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:181)
	... 55 more
```

**Comment by aldenml** [comment]
This is due to the removal of our custom lucene and the use of the one from maven. We should be able to work it out.

**Comment by gubatron** [comment]
maybe tis time I take a look at this and remove lucene, and use maybe something simpler, a-la james gosling (or sqlite)

**Comment by gubatron** [comment]
That library has lots of potential. Which reminds me, we need to talk about a process to build a separate FrostWire Player app for android. I'm starting to think more and more it's a good idea to separate the two sometime down the line, and promote each separately, maybe get a set of developers to help us clean that code and move it forward, it's a nice player after all.

**Comment by gubatron** [comment]
@muckachina  for now, it allows creating, adding, deleting songs from playlists created with older FrostWire.

PLEASE NOTE: **Playlist search is still broken**, even on newer playlists, working on it as a related issue. It still tries to look for the old `org.h2.fulltext.FullTextLucene2` class. #postHackIssues

**Comment by gubatron** [comment]
playlist search now works.

**Comment by gubatron** [comment]
isn't search working inside search?

Search in the whole Library is contextual, if we want to change that to be globally inside the search then open another ticket. As this is a major architectural change in the library. As of now, if you notice, you search only within the selected tree item.

Please close it if it works.

**Comment by muckachina** [comment]
Ok closing... 

Just to make sure, I'm searching at the top left of the screen where it says "Search your Audio", that's is working properly, it filters the list.

**Comment by gubatron** [comment]
yup, that's the final fix.
