### ISSUE TITLE
[desktop] crash on 6.4.0 build 207 (Linux)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#217]
(On a super old machine, still running kernel 2.6.32, I'm running 4.4.0-43!, the java is newer though)

```
FrostWire version 6.4.0 build 207
Java version 1.8.0_102 from Oracle Corporation
Linux v. 2.6.32 on amd64
Free/total memory: 76285432/109576192

FATAL ERROR!

java.lang.ExceptionInInitializerError
        at com.frostwire.gui.tabs.SearchTab.getComponent(Unknown Source)
        at com.frostwire.gui.tabs.SearchTransfersTab.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.MainFrame.buildTabs(Unknown Source)
        at com.limegroup.gnutella.gui.MainFrame.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.GUIMediator.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.GUIMediator.instance(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer$5.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 420857456
        at javax.swing.plaf.nimbus.NimbusDefaults$LazyStyle.matches(NimbusDefaults.java:1481)
        at javax.swing.plaf.nimbus.NimbusDefaults$LazyStyle.matches(NimbusDefaults.java:1469)
        at javax.swing.plaf.nimbus.NimbusDefaults.getStyle(NimbusDefaults.java:1158)
        at javax.swing.plaf.nimbus.NimbusLookAndFeel$1.getStyle(NimbusLookAndFeel.java:111)
        at javax.swing.plaf.synth.SynthLookAndFeel.getStyle(SynthLookAndFeel.java:235)
        at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:256)
        at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
        at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
        at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
        at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
        at com.frostwire.gui.theme.SkinPanelUI.installUI(Unknown Source)
        at javax.swing.JComponent.setUI(JComponent.java:666)
        at javax.swing.JPanel.setUI(JPanel.java:153)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:109)
        at javax.swing.JPanel.<init>(JPanel.java:117)
        at com.limegroup.gnutella.gui.BoxPanel.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.search.SearchResultDisplayer.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.search.SearchMediator.getSearchResultDisplayer(Unknown Source)
        at com.limegroup.gnutella.gui.search.SearchMediator.<init>(Unknown Source)
        at com.limegroup.gnutella.gui.search.SearchMediator.<clinit>(Unknown Source)
        ... 21 more


-- class path --
frostwire.jar
-- listing session information --
Current thread: main
Active Threads: 10
Peak Number of Thread: 19
System Load Avg: 0.51
Objects Pending GC: 0
Free Space In Settings: 387738210304
Free Space In Incomplete:
Heap Memory Usage: init = 132120576(129024K) used = 33290760(32510K) committed = 109576192(107008K) max = 1873805312(1829888K)
Non-Heap Memory Usage: init = 2555904(2496K) used = 48680712(47539K) committed = 49610752(48448K) max = -1(-1K)

-- listing threads --
Image Fetcher 0: 1
Deadlock Detection Thread: 1
SessionManager-alertsLoop: 1
Image Fetcher 3: 1
OkHttp ConnectionPool: 1
main: 1
DelayedGUI: 1
AWT-EventQueue-0: 1
Thread-2: 1
MVStore background writer nio:/root/.frostwire5/library_db/library_db.mv.db: 1


-- listing properties --
INSTALLED=true
UX_STATS_ENABLED=false
COUNTRY=
BTMEDIATOR_COLUMN_SORT_INDEX=16
WINDOW_Y=84
LAST_EXPIRE_TIME=1477059721969
WINDOW_X=171
```

**Comment by gubatron** [comment]
won't fix, very hard to replicate, will blame it on the old ass kernel maybe having an integer overflow issue with the super modern java 1.8 the user was running, user needs to upgrade to a newer kernel.
