### ISSUE TITLE
[android/runtime exception] torrent_handle_torrent_file_ptr

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#221]
This one came out on Android 5.1 and Android 6.0, both reports on HTC Desire 626s

```
java.lang.RuntimeException: invalid torrent handle used
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.torrent_handle_torrent_file_ptr(Native Method)
	at com.frostwire.jlibtorrent.swig.torrent_handle.torrent_file_ptr(torrent_handle.java:351)
	at com.frostwire.jlibtorrent.TorrentHandle.torrentFile(TorrentHandle.java:167)
	at com.frostwire.bittorrent.BTDownload.getProgress(BTDownload.java:215)
	at com.frostwire.bittorrent.BTDownload.isComplete(BTDownload.java:255)
	at com.frostwire.android.gui.transfers.UIBittorrentDownload.isComplete(UIBittorrentDownload.java:271)
	at com.frostwire.android.gui.transfers.TransferManager.getActiveDownloads(TransferManager.java:179)
	at com.frostwire.android.gui.fragments.TransfersFragment.onTime(TransfersFragment.java:158)
	at com.frostwire.android.gui.fragments.TransfersFragment$ButtonTabListener.onClick(TransfersFragment.java:793)
	at com.frostwire.android.gui.fragments.TransfersFragment$ButtonTabListener.onClick(TransfersFragment.java:781)
	at com.frostwire.android.gui.views.ClickAdapter.onClick(ClickAdapter.java:44)
	at android.view.View.performClick(View.java:5232)
	at android.widget.CompoundButton.performClick(CompoundButton.java:122)
	at com.frostwire.android.gui.fragments.TransfersFragment.selectStatusTab(TransfersFragment.java:263)
	at com.frostwire.android.gui.activities.internal.MainController.showTransfers(MainController.java:73)
	at com.frostwire.android.gui.activities.MainActivity.onNewIntent(MainActivity.java:323)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1258)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1275)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2645)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2663)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2672)
	at android.app.ActivityThread.access$1700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5885)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

This one is for @aldenml

**Comment by aldenml** [comment]
fixed with https://github.com/frostwire/frostwire-jlibtorrent/commit/054c3207b1140998b824b119eb658960bb8791fc, happening in desktop too
