### ISSUE TITLE
[android] Removing libRSSupport.so and librsjni.so

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#276]
```
$ cd x86/
Angels-MacBook-Pro:x86 gubatron$ ls -lh
total 13632
-rw-r--r--  1 gubatron  501   1.1M Dec 31  1979 libRSSupport.so
-rw-r--r--  1 gubatron  501   5.5M Dec 31  1979 libjlibtorrent.so
-rw-r--r--  1 gubatron  501    58K Dec 31  1979 librsjni.so
Angels-MacBook-Pro:x86 gubatron$ cd ..
Angels-MacBook-Pro:lib gubatron$ cd ../armeabi-v7a/
Angels-MacBook-Pro:armeabi-v7a gubatron$ ls -lh
total 11648
-rw-r--r--  1 gubatron  501   898K Dec 31  1979 libRSSupport.so
-rw-r--r--  1 gubatron  501   4.8M Dec 31  1979 libjlibtorrent.so
-rw-r--r--  1 gubatron  501    50K Dec 31  1979 librsjni.so
```

it seems adding RenderScript (to just do 1 blur) is making the installer 2.1M larger than necessary.

One would think that libRSSupport.so and librsjni.so would be shared libraries in the operating system, so before we go ahead and simply remove RenderScript, I'll try to see if RenderScript can be used without including these libraries.

If we can't, then @aldenml will remove RenderScript and replace it with the old picasso based blur transformation.

**Comment by gubatron** [comment]
ok, that didn't fly:
```
.android.gms-play-services-basement-10.0.1_6706008bb0e31293d8734a2190a2d6f674f40c36-
12-02 17:21:42.027  1859  1859 D Error   : ERR: file=RenderScript.java
12-02 17:21:42.027  1859  1859 D Error   : ERR: class=android.support.v8.renderscript.RenderScript
12-02 17:21:42.027  1859  1859 D Error   : ERR: method=internalCreate line=1434
12-02 17:21:42.027  1859  1859 D Error   : ERR: stack=java.lang.RuntimeException: Transformation default_blur crashed with exception.
12-02 17:21:42.027  1859  1859 D Error   : 	at com.squareup.picasso.BitmapHunter$3.run(BitmapHunter.java:434)
12-02 17:21:42.027  1859  1859 D Error   : 	at android.os.Handler.handleCallback(Handler.java:739)
12-02 17:21:42.027  1859  1859 D Error   : 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-02 17:21:42.027  1859  1859 D Error   : 	at android.os.Looper.loop(Looper.java:152)
12-02 17:21:42.027  1859  1859 D Error   : 	at android.app.ActivityThread.main(ActivityThread.java:5497)
12-02 17:21:42.027  1859  1859 D Error   : 	at java.lang.reflect.Method.invoke(Native Method)
12-02 17:21:42.027  1859  1859 D Error   : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-02 17:21:42.027  1859  1859 D Error   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-02 17:21:42.027  1859  1859 D Error   : Caused by: android.support.v8.renderscript.RSRuntimeException: Error loading RS Compat library: java.lang.UnsatisfiedLinkError
```

We'll have to just remove RenderScript altogether and just blur a little slower. not worth the 2.1Mb.

**Comment by grzesiekrzaca** [comment]
the file is libRSSupport.so so maybe it's just there because we have the target of API 16 and use the support version. So (I think) we could use the old blur on API 16 and when the library is in the OS (17+) we would use RS. (Unless it packs RSSupport anyway)
