### ISSUE TITLE
[CRASH] FrostWire 6.4.3 crashes on startup on MacOS Yosemite

### ISSUE THREAD

**Issue by cateye** [frostwire/frostwire#326]
Something must have gone wrong with the new jlibtorrent .dylib linkage.
CC: @aldenml 
```
os.name="Mac OS X"
Exception in thread "main" java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(Unknown Source)
	at com.limegroup.gnutella.gui.Main.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /Applications/FrostWire.app/Contents/MacOS/libjlibtorrent.dylib: dlopen(/Applications/FrostWire.app/Contents/MacOS/libjlibtorrent.dylib, 1): no suitable image found.  Did find:
	/Applications/FrostWire.app/Contents/MacOS/libjlibtorrent.dylib: code signature invalid for '/Applications/FrostWire.app/Contents/MacOS/libjlibtorrent.dylib'

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
```

**Comment by aldenml** [comment]
The error `code signature invalid for '/Applications/FrostWire.app/Contents/MacOS/libjlibtorrent.dylib'` is clear, I will check with @gubatron what happened in the installer
