### ISSUE TITLE
[android] Mysterious crash with touch handler on `My Files`

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#39]
A few crashlogs let me see it had something to do with an uninitialized touch handler. I've put a try/catch on a parent abstract class to prevent the crash but the source of the problem remains a mystery.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getImportantForAccessibility()' on a null object reference
	at android.widget.AbsListView.obtainView(AbsListView.java:2486)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1659)
	at android.widget.AbsListView.onLayout(AbsListView.java:2274)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15767)
	at android.view.ViewGroup.layout(ViewGroup.java:5053)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2229)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1138)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6154)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
	at android.view.Choreographer.doCallbacks(Choreographer.java:596)
	at android.view.Choreographer.doFrame(Choreographer.java:557)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5725)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Comment by gubatron** [comment]
On staged roll out [frostwire-android-1.6.9-build-228](https://github.com/frostwire/frostwire/releases/tag/frostwire-android-1.6.9-build-228) I've put a try/catch on a parent abstract class to prevent the crash but the source of the problem remains a mystery to see if this stops the crash from happening.

The cause is still not known.

**Comment by gubatron** [comment]
bad news, the bug just popped up again on build 228.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getImportantForAccessibility()' on a null object reference
	at android.widget.AbsListView.obtainView(AbsListView.java:2403)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1659)
	at android.widget.AbsListView.onLayout(AbsListView.java:2191)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

Maybe something to do with the drawer menu.

**Comment by aldenml** [comment]
Yes, maybe it's related to the drawer

**Comment by aldenml** [comment]
@gubatron We have reports of this issue, but in the details of the crash we are not getting the latest version. Let's wait to see more reporting before any conclusion.

**Comment by aldenml** [comment]
@gubatron For review and testing

**Comment by gubatron** [comment]
In 24 hours, `build 231` has not reported another crash. It seems the offender, or the trigger for the offending bug happens because of Flurry.

it might be worth reading any caveats in the Flurry documentation I may have unnoticed.

**Comment by aldenml** [comment]
I will close this since the mystery is over an the crash is gone. The return of Flurry is another task.
