### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.session_stats_header_alert_priority_get()I

### ISSUE THREAD

**Issue by unnivm** [frostwire/frostwire#404]
I am getting the following error while running this application after building from the source.

I have taken frostwire-6.4.6-build-223 source  and added the dlls in native folder.

java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.session_stats_header_alert_priority_get()I
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.session_stats_header_alert_priority_get(Native Method)
	at com.frostwire.jlibtorrent.swig.session_stats_header_alert.<clinit>(session_stats_header_alert.java:54)
	at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(AlertType.java:99)
	at com.frostwire.jlibtorrent.SessionManager.<clinit>(SessionManager.java:24)
	at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Initializer.java:475)
	at com.limegroup.gnutella.gui.Initializer.initialize(Initializer.java:112)
	at com.limegroup.gnutella.gui.GUILoader.load(GUILoader.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.limegroup.gnutella.gui.Main.main(Main.java:84)

Thanks
Unni

**Comment by aldenml** [comment]
You need to put the corresponding jlibtorrent native libraries in the `-Djava.library.path=`, they are here https://github.com/frostwire/frostwire/tree/master/desktop/lib/native
