### ISSUE TITLE
[android] Not showing update message on first run

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#418]
```
04-07 08:32:34.859 31276 31306 I SoftwareUpdater: handleOTAUpdate(): Finished downloading update... (2920bf74fe52c5c806801079cb65977a)
04-07 08:32:34.876  1188  4389 W qti_sensors_hal: timestampCalc: Adjusting timestamp for rollover: 396150143103238, 1
04-07 08:32:34.927 31276 31306 I SoftwareUpdater: checkMD5(expected=2920bf74fe52c5c806801079cb65977a, checked=2920bf74fe52c5c806801079cb65977a)
04-07 08:32:34.927 31276 31306 I SoftwareUpdater: handleOTAUpdate(): downloadedLatestFrostWire(2920bf74fe52c5c806801079cb65977a) -> true
04-07 08:32:34.928 31276 31276 I SoftwareUpdater: notifyUserAboutUpdate(): showing update dialog.

04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: Failed to notify update
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1411)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1429)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.DialogFragment.show(DialogFragment.java:230)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.views.AbstractDialog.show(AbstractDialog.java:100)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater.notifyUserAboutUpdate(SoftwareUpdater.java:250)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater$1.onPostExecute(SoftwareUpdater.java:161)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater$1.onPostExecute(SoftwareUpdater.java:109)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.os.Looper.loop(Looper.java:152)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-07 08:32:34.933 31276 31276 E FW.SoftwareUpdater: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-07 08:32:34.944  1188  4389 W qti_sensors_hal: timestampCalc: Adjusting timestamp for rollover: 396150210272428, 1
```

**Comment by aldenml** [comment]
I can't replicate this issue, do you have the steps to do it?

**Comment by gubatron** [comment]
1. Make build number 355 and point Constants::SERVER_UPDATE_URL to update1.frostwire.com
4. ./gradlew assembleRelease
3. Uninstall FW if it was installed
4. Install, Run, and `adb logcat | grep SoftwareUpdater`

I'm on Android 7.0
Just ran again to see the issue of "Plus Plus" on the menu, and got this on my first run:
```
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: Failed to notify update
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1411)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1429)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.DialogFragment.show(DialogFragment.java:230)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.views.AbstractDialog.show(AbstractDialog.java:100)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater.notifyUserAboutUpdate(SoftwareUpdater.java:250)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater$1.onPostExecute(SoftwareUpdater.java:161)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.frostwire.android.gui.SoftwareUpdater$1.onPostExecute(SoftwareUpdater.java:109)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.os.Looper.loop(Looper.java:152)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-07 16:52:38.918 18726 18726 E FW.SoftwareUpdater: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by gubatron** [comment]
another bug, is that I'm not seeing the update icon on the menu either, will try to fix both.
