### ISSUE TITLE
[android/crash] Picasso/OOM

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#478]
```
java.lang.OutOfMemoryError: 
  at java.lang.Thread.nativeCreate(Native Method:0)
  at java.lang.Thread.start(Thread.java:730)
  at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
  at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
  at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:601)
  at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:202)
  at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:175)
  at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:469)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by gubatron** [comment]
It'd be awesome if you took a look at this one @aldenml

**Comment by gubatron** [comment]
the only prominent crash so far on build 395

**Comment by aldenml** [comment]
Sure, opened in front of me

**Comment by gubatron** [comment]
![screen shot 2017-06-15 at 9 42 08 am](https://user-images.githubusercontent.com/163977/27189546-f0031806-51ae-11e7-8617-b3bb3b1c5e56.png)


something new in the code after 393

**Comment by aldenml** [comment]
Something must be have been changed in the internal logic of Picasso that now it's more aggressive in submitting queued tasks to the thread pool. This should fix it, but I have a pending review to see how many actual native threads we are launching in the app: https://github.com/frostwire/frostwire/commit/6411917c65a78510b0f49ae7c561aada844fcb81

**Comment by gubatron** [comment]
excellent, I'll make a new build and put it right up to see if it goes away
