### ISSUE TITLE
[android] Possible Context Leak at HandpickedTorrentDownloadDialog$OnStartDownloadsClickListener.startTorrentPartialDownload(

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#518]
```
07-14 07:11:53.854 24777 24777 E AndroidRuntime: java.lang.RuntimeException: Runnable contains context, possible context leak
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at com.frostwire.android.gui.services.EngineThreadPool.execute(EngineThreadPool.java:45)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at com.frostwire.android.gui.dialogs.HandpickedTorrentDownloadDialog$OnStartDownloadsClickListener.startTorrentPartialDownload(HandpickedTorrentDownloadDialog.java:315)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at com.frostwire.android.gui.dialogs.HandpickedTorrentDownloadDialog$OnStartDownloadsClickListener.onClick(HandpickedTorrentDownloadDialog.java:289)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.view.View.performClick(View.java:5233)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.view.View$PerformClick.run(View.java:21209)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:152)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5497)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-14 07:11:53.854 24777 24777 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-14 07:11:53.856 24777 24777 D AppTracker: App Event: crash
```

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire/commit/5b2856f493c4947581ed654332426261aa508b90
