### ISSUE TITLE
[common] YT decoder: Illegal hex characters in escape (%) pattern

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#677]
```
03-12 22:56:15.893 10586-10929/com.frostwire.android W/System.err: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : % f
03-12 22:56:15.900 10586-10929/com.frostwire.android W/System.err:     at java.net.URLDecoder.decode(URLDecoder.java:177)
03-12 22:56:15.900 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.jd.Encoding.htmlDecode(Encoding.java:35)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeExtractor.getLinks(YouTubeExtractor.java:276)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeExtractor.extract(YouTubeExtractor.java:65)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeSearchPerformer.crawlResult(YouTubeSearchPerformer.java:67)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeSearchPerformer.crawlResult(YouTubeSearchPerformer.java:40)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.CrawlPagedWebSearchPerformer.crawl(CrawlPagedWebSearchPerformer.java:158)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at com.frostwire.search.SearchManager$CrawlTask.run(SearchManager.java:309)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-12 22:56:15.901 10586-10929/com.frostwire.android W/System.err:     at java.lang.Thread.run(Thread.java:764)
03-12 22:56:16.124 10586-10923/com.frostwire.android W/System.err: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : % f
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at java.net.URLDecoder.decode(URLDecoder.java:177)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.jd.Encoding.htmlDecode(Encoding.java:35)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeExtractor.getLinks(YouTubeExtractor.java:276)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeExtractor.extract(YouTubeExtractor.java:65)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeSearchPerformer.crawlResult(YouTubeSearchPerformer.java:67)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.youtube.YouTubeSearchPerformer.crawlResult(YouTubeSearchPerformer.java:40)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.CrawlPagedWebSearchPerformer.crawl(CrawlPagedWebSearchPerformer.java:158)
03-12 22:56:16.125 10586-10923/com.frostwire.android W/System.err:     at com.frostwire.search.SearchManager$CrawlTask.run(SearchManager.java:309)
03-12 22:56:16.126 10586-10923/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-12 22:56:16.126 10586-10923/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-12 22:56:16.126 10586-10923/com.frostwire.android W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

**Comment by aldenml** [comment]
This is a expected error, and it's just logged, I will comment that printStackTrace and do a minor code cleanup
