### ISSUE TITLE
[desktop] OOM @ at com.frostwire.database.sqlite.SQLiteDatabase.delete

### ISSUE THREAD

**Issue by marcelinkaaa** [frostwire/frostwire#679]
```
[Marcelinkaaa@mbp ~/Library/Preferences/FrostWire5 (master *)]$ du -hs dbs
744M	dbs
```

When I try to reset the smart search database cache I see this Out of memory error.
When the app tries to do this on startup or shutdown it keeps failing as well and may crash on shutdown.

```
org.h2.jdbc.JdbcSQLException: Out of memory.; SQL statement:
DELETE FROM CacheData [90108-193]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.convert(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.executeSql(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.delete(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.delete(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.clear(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.lambda$new$32(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Requested memory: 2517007
	at org.h2.mvstore.DataUtils.newBytes(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.readValue(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.readValue(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.read(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$VersionedValueType.read(Unknown Source)
	at org.h2.mvstore.Page.read(Unknown Source)
	at org.h2.mvstore.Page.read(Unknown Source)
	at org.h2.mvstore.MVStore.readPage(Unknown Source)
	at org.h2.mvstore.MVMap.readPage(Unknown Source)
	at org.h2.mvstore.Page.getChildPage(Unknown Source)
	at org.h2.mvstore.Cursor.fetchNext(Unknown Source)
	at org.h2.mvstore.Cursor.next(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.fetchNext(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.next(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.next(Unknown Source)
	at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(Unknown Source)
	at org.h2.index.IndexCursor.next(Unknown Source)
	at org.h2.table.TableFilter.next(Unknown Source)
	at org.h2.command.dml.Delete.update(Unknown Source)
	at org.h2.command.CommandContainer.update(Unknown Source)
	... 9 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.h2.mvstore.DataUtils.newBytes(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.readValue(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.readValue(Unknown Source)
	at org.h2.mvstore.db.ValueDataType.read(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$VersionedValueType.read(Unknown Source)
	at org.h2.mvstore.Page.read(Unknown Source)
	at org.h2.mvstore.Page.read(Unknown Source)
	at org.h2.mvstore.MVStore.readPage(Unknown Source)
	at org.h2.mvstore.MVMap.readPage(Unknown Source)
	at org.h2.mvstore.Page.getChildPage(Unknown Source)
	at org.h2.mvstore.Cursor.fetchNext(Unknown Source)
	at org.h2.mvstore.Cursor.next(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.fetchNext(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.next(Unknown Source)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$2.next(Unknown Source)
	at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(Unknown Source)
	at org.h2.index.IndexCursor.next(Unknown Source)
	at org.h2.table.TableFilter.next(Unknown Source)
	at org.h2.command.dml.Delete.update(Unknown Source)
	at org.h2.command.CommandContainer.update(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.executeSql(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.delete(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.delete(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.clear(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.lambda$new$32(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator$$Lambda$47/510624255.run(Unknown Source)
	... 1 more

Mar 14, 2018 11:43:12 AM SQLiteDatabase 
INFO: Error performing SQL statement: SELECT id FROM CacheData ORDER BY dateAdded DESC
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.engine.Database.checkPowerOff(Unknown Source)
	at org.h2.command.Command.executeQuery(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.rawQueryWithFactory(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.query(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.numEntries(Unknown Source)
	at com.frostwire.search.CrawlPagedWebSearchPerformer.getCacheNumEntries(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.getTotalTorrents(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem$2.run(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Mar 14, 2018 11:43:12 AM SQLiteDatabase 
INFO: Error performing SQL statement: SELECT id FROM CacheData ORDER BY dateAdded DESC
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.engine.Database.checkPowerOff(Unknown Source)
	at org.h2.command.Command.executeQuery(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.rawQueryWithFactory(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.query(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.numEntries(Unknown Source)
	at com.frostwire.search.CrawlPagedWebSearchPerformer.getCacheNumEntries(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.getTotalTorrents(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem$2.run(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Mar 14, 2018 11:43:21 AM SQLiteDatabase 
INFO: Error performing SQL statement: DELETE FROM CacheData
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.engine.Session.getTransaction(Unknown Source)
	at org.h2.engine.Session.getStatementSavepoint(Unknown Source)
	at org.h2.engine.Session.setSavepoint(Unknown Source)
	at org.h2.command.Command.executeUpdate(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.executeSql(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.delete(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.delete(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.clear(Unknown Source)
	at com.frostwire.search.CrawlPagedWebSearchPerformer.clearCache(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.clearCache(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem.resetSmartSearchDB(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem$1$1.run(Unknown Source)
	at com.limegroup.gnutella.gui.GUIMediator.safeInvokeLater(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Mar 14, 2018 11:43:21 AM SQLiteDatabase 
INFO: Error performing SQL statement: SELECT id FROM CacheData ORDER BY dateAdded DESC
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.message.DbException.get(Unknown Source)
	at org.h2.engine.Database.checkPowerOff(Unknown Source)
	at org.h2.command.Command.executeQuery(Unknown Source)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteDatabase.rawQueryWithFactory(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.database.sqlite.SQLiteQueryBuilder.query(Unknown Source)
	at com.frostwire.search.CrawlCacheDB.query(Unknown Source)
	at com.frostwire.search.DatabaseCrawlCache.numEntries(Unknown Source)
	at com.frostwire.search.CrawlPagedWebSearchPerformer.getCacheNumEntries(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.getTotalTorrents(Unknown Source)
	at com.limegroup.gnutella.gui.options.panes.SmartSearchDBPaneItem$2.run(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at org.limewire.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by aldenml** [comment]
very strange, are you running any VMware VM?

**Comment by marcelinkaaa** [comment]
Not running any VM

**Comment by aldenml** [comment]
ok, save that folder `FrostWire5` to allow for test when I have a fix for it please

**Comment by muckachina** [comment]
I told her to install from scratch to check If this is related to Windows users report that solve the issue when deleting FrostWire5 folder

**Comment by aldenml** [comment]
I doubt that solve the problem for her, since that's inside the preferences folder, that should persist from install to install

**Comment by marcelinkaaa** [comment]
Yes installed fresh, the problem persists.

**Comment by aldenml** [comment]
ok, just take that folder, save it while I take a look at it, and remove it in order to continue to use FW

**Comment by gubatron** [comment]
I copied the "db" folder (744M) back to her Preferences and the crash re-appears.
I think the fix might be doing a hard deletion of the folder without getting into `db.delete()` SQL calls.

My guess is that the database implementation is loading way too many records (doing something else in between) in the heap and it gets the OOM error.

As soon as you delete that "db" folder the problem goes away.

It's a problem that I didn't fix all the way, and it's manifesting because FrostWire is detecting that the folder got too big, it's just not able to wipe it out correctly.

**Comment by muckachina** [comment]
Then it should be connected with Windows reports, she had the old files in Transfer when launched the app again which means she didn't install from scratch, after deleting old files from Transfer the problem disappeared for a while.

A lot of Windows users solve the problem installing from scratch after the Transfer list is cleared

**Comment by aldenml** [comment]
This query should be the root `SELECT id FROM CacheData ORDER BY dateAdded DESC`

**Comment by gubatron** [comment]
problem solved, no more OOM on @marcelinkaaa's.
`TRUNCATE TABLE` did the trick.

Whenever the first `SearchMediator` instance is created a check for the size of the DB folder is done, if too big, the `TRUNCATE TABLE` call will happen.

**Comment by gubatron** [comment]
Please give it a try now @muckachina , for it to work you need to have a search database bigger than 250MB.

**Comment by muckachina** [comment]
I haven't been able to reproduce here yet on Mac or Windows but I'll keep trying, I'll pull and check
