### ISSUE TITLE
[desktop] TransferDetailGeneral crash - invalid torrent handle used

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#748]
```
FrostWire version 6.7.0 build 262
Java version 1.8.0_162 from Oracle Corporation
Mac OS X v. 10.13.4 on x86_64
Free/total memory: 91747504/196608000

java.lang.RuntimeException: invalid torrent handle used
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.torrent_handle_status__SWIG_0(Native Method)
        at com.frostwire.jlibtorrent.swig.torrent_handle.status(Unknown Source)
        at com.frostwire.jlibtorrent.TorrentHandle.status(Unknown Source)
        at com.frostwire.jlibtorrent.TorrentHandle.status(Unknown Source)
        at com.frostwire.gui.components.transfers.TransferDetailGeneral.updateData(Unknown Source)
        at com.frostwire.gui.components.transfers.TransferDetailComponent.refresh(Unknown Source)
        at com.limegroup.gnutella.gui.GUIMediator.refreshGUI(Unknown Source)
```

**Comment by gubatron** [comment]
5 crash reports so far, all the same crash.

cool to have (even a bare bones) crash report system

**Comment by gubatron** [comment]
think this will avoid the crash @aldenml (No rush to answer, still waiting for more crashes)
https://github.com/frostwire/frostwire/commit/fa2a19cf5cdbce7f96cf32559346df97f0549f78

**Comment by aldenml** [comment]
check my comment in the commit, I think we should take a look at the situation of this "details components" still working while not needed anymore.
