### ISSUE TITLE
[desktop/crash] SearchTab.getComponent() -> java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#749]
```
version=6.6.8
build=260
==========
FrostWire version 6.6.8 build 260
Java version 1.8.0_162 from Oracle Corporation
Windows 10 v. 10.0 on x86
Free/total memory: 8595680/25370624

FATAL ERROR!

java.lang.ExceptionInInitializerError
	at com.frostwire.gui.tabs.SearchTab.getComponent(Unknown Source)
	at com.frostwire.gui.tabs.SearchTransfersTab.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.MainFrame.buildTabs(Unknown Source)
	at com.limegroup.gnutella.gui.MainFrame.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.GUIMediator.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.GUIMediator.instance(Unknown Source)
	at com.limegroup.gnutella.gui.Initializer$5.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter.checkText(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at com.limegroup.gnutella.gui.search.SchemaBox.addSchemas(Unknown Source)
	at com.limegroup.gnutella.gui.search.SchemaBox.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchResultMediator.createSchemaBox(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchResultMediator.setupMainPanelBase(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchResultMediator.setupMainPanel(Unknown Source)
	at com.limegroup.gnutella.gui.tables.AbstractTableMediator.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchResultMediator.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchResultDisplayer.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.getSearchResultDisplayer(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.<init>(Unknown Source)
	at com.limegroup.gnutella.gui.search.SearchMediator.<clinit>(Unknown Source)
	... 21 more
```

**Comment by gubatron** [comment]
Other than a try/catch, no clue how to fix this one @aldenml

**Comment by aldenml** [comment]
This is a bad translation more likely with an rtl language (and there are many), the try-catch is a solution is aceptable: https://github.com/frostwire/frostwire/commit/cb008b509e492514d9d2287d890da969cb1fa4cb
