### ISSUE TITLE
[desktop] Crash on startup (Windows 7 and 10) -  UnsatisfiedLinkError libtorrent_jni.settings_pack_support_share_mode_get

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#759]
Quite a few instances, not sure if it's due to bad installations or due to missing symbol.

```
version=6.7.0
build=264
==========
FrostWire version 6.7.0 build 264
Java version 1.8.0_162 from Oracle Corporation
Windows 10 v. 10.0 on x86
Free/total memory: 12695768/28557312

FATAL ERROR!

java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.settings_pack_support_share_mode_get()I
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.settings_pack_support_share_mode_get(Native Method)
	at com.frostwire.jlibtorrent.swig.settings_pack$bool_types.<clinit>(Unknown Source)
	at com.frostwire.bittorrent.BTEngine.start(Unknown Source)
	at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Unknown Source)
	at com.limegroup.gnutella.gui.Initializer.initialize(Unknown Source)
	at com.limegroup.gnutella.gui.GUILoader.load(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.limegroup.gnutella.gui.Main.main(Unknown Source)


-- class path --
frostwire.jar
-- listing session information --
Current thread: main
Active Threads: 7
Peak Number of Thread: 16
System Load Avg: -1.0
Objects Pending GC: 0
Free Space In Settings: 24437727232
Free Space In Incomplete: 
Heap Memory Usage: init = 16777216(16384K) used = 15861544(15489K) committed = 28557312(27888K) max = 518979584(506816K)
Non-Heap Memory Usage: init = 163840(160K) used = 17872232(17453K) committed = 18251776(17824K) max = -1(-1K)
```

```
version=6.7.0
build=264
==========
FrostWire version 6.7.0 build 264
Java version 1.8.0_162 from Oracle Corporation
Windows 7 v. 6.1 on x86
Free/total memory: 9372544/16318464

FATAL ERROR!

java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.settings_pack_support_share_mode_get()I
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.settings_pack_support_share_mode_get(Native Method)
	at com.frostwire.jlibtorrent.swig.settings_pack$bool_types.<clinit>(Unknown Source)
	at com.frostwire.bittorrent.BTEngine.start(Unknown Source)
	at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Unknown Source)
	at com.limegroup.gnutella.gui.Initializer.initialize(Unknown Source)
	at com.limegroup.gnutella.gui.GUILoader.load(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.limegroup.gnutella.gui.Main.main(Unknown Source)


-- class path --
frostwire.jar
-- listing session information --
Current thread: main
Active Threads: 4
Peak Number of Thread: 11
System Load Avg: -1.0
Objects Pending GC: 0
Free Space In Settings: 685116047360
Free Space In Incomplete: 
Heap Memory Usage: init = 16777216(16384K) used = 7005672(6841K) committed = 16318464(15936K) max = 518979584(506816K)
Non-Heap Memory Usage: init = 163840(160K) used = 14028648(13699K) committed = 14254080(13920K) max = -1(-1K)

```

**Comment by aldenml** [comment]
The symbol is there, otherwise it fails always. As for the reason, we have seen antivirus causing incomplete installations, but sometimes it's just the JVM, this error is haunting us for years. I think the situation could improve with the `jmod`, in which we can finally embed binaries, that needs upgrading to java 9.
