### ISSUE TITLE
[android] Android Q music playback not working

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#848]
Found the source of the issue, it seems the schema may have changed, pasting the entire stack trace that stems from `MusicPlaybackService::openCursorAndGoToFirst(Uri uri, String[] projection,String selection, String[] selectionArgs)`.

it breaks here:
```java
try {
    c = getContentResolver().query(uri, projection, selection, selectionArgs, null);
} catch (Throwable t) {
    t.printStackTrace();
    return null;
}
```

That query breaks with the following:
```
2019-10-01 11:09:31.782 15405-15479/com.frostwire.android W/System.err: java.lang.IllegalArgumentException: Invalid column audio._id AS _id
2019-10-01 11:09:31.782 15405-15479/com.frostwire.android W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
2019-10-01 11:09:31.783 15405-15479/com.frostwire.android W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
2019-10-01 11:09:31.783 15405-15479/com.frostwire.android W/System.err:     at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
2019-10-01 11:09:31.783 15405-15479/com.frostwire.android W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:944)
2019-10-01 11:09:31.783 15405-15479/com.frostwire.android W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:880)
2019-10-01 11:09:31.784 15405-15479/com.frostwire.android W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:836)
2019-10-01 11:09:31.784 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.openCursorAndGoToFirst(MusicPlaybackService.java:1243)
2019-10-01 11:09:31.785 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.updateCursor(MusicPlaybackService.java:1214)
2019-10-01 11:09:31.784 15405-15609/com.frostwire.android I/ImageLoader: Using album_art path for uri: content://media/external/audio/albums/5
2019-10-01 11:09:31.789 15405-15583/com.frostwire.android I/ImageLoader: Using album_art path for uri: content://media/external/audio/albums/4
2019-10-01 11:09:31.790 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.updateCursor(MusicPlaybackService.java:1208)
2019-10-01 11:09:31.790 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.openCurrentAndMaybeNext(MusicPlaybackService.java:1299)
2019-10-01 11:09:31.790 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.openCurrentAndNext(MusicPlaybackService.java:1277)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService.open(MusicPlaybackService.java:2220)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.MusicPlaybackService$ServiceStub.open(MusicPlaybackService.java:3144)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.andrew.apollo.utils.MusicUtils.playAll(MusicUtils.java:804)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.gui.services.ApolloMediaPlayer.play(ApolloMediaPlayer.java:43)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.gui.util.UIUtils.playEphemeralPlaylistTask(UIUtils.java:525)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.gui.util.UIUtils.lambda$7ABln0ZIqnH0jS6eH3G5o0NcPoM(Unknown Source:0)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.gui.util.-$$Lambda$UIUtils$7ABln0ZIqnH0jS6eH3G5o0NcPoM.run(Unknown Source:4)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.util.Asyncs.lambda$async$9(Asyncs.java:137)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.util.-$$Lambda$Asyncs$_SHbUFCx_jodI7UBFe_2wC72vEk.run(Unknown Source:2)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.util.Asyncs.lambda$invokeAsyncSupport$32(Asyncs.java:380)
2019-10-01 11:09:31.792 15405-15479/com.frostwire.android W/System.err:     at com.frostwire.android.util.-$$Lambda$Asyncs$6mnyDfjODWzTGIRho6tr-HrdXZc.run(Unknown Source:8)
2019-10-01 11:09:31.794 15405-15479/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-10-01 11:09:31.794 15405-15479/com.frostwire.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-10-01 11:09:31.794 15405-15479/com.frostwire.android W/System.err:     at java.lang.Thread.run(Thread.java:919)
2019-10-01 11:09:31.794 15405-15479/com.frostwire.android I/MusicPlaybackService: setNextTrack: next play position = 1
2019-10-01 11:09:31.794 15405-15479/com.frostwire.android I/MusicPlaybackService: Next media player is current one, continuing
2019-10-01 11:09:31.798 15405-15479/com.frostwire.android W/AudioManager: Use of stream types is deprecated for operations other than volume control
2019-10-01 11:09:31.798 15405-15479/com.frostwire.android W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2019-10-01 11:09:31.798 15405-15485/com.frostwire.android V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2019-10-01 11:09:31.798 15405-15485/com.frostwire.android V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2019-10-01 11:09:31.796 15405-15608/com.frostwire.android I/ImageLoader: Using album_art path for uri: content://media/external/audio/albums/2
2019-10-01 11:09:31.799 15405-15479/com.frostwire.android I/MusicPlaybackService: Starting playback: audio focus request status = 1
2019-10-01 11:09:31.801 15405-15610/com.frostwire.android I/ImageLoader: Using album_art path for uri: content://media/external/audio/albums/5
2019-10-01 11:09:31.803 15405-15485/com.frostwire.android W/MediaPlayer: Couldn't open content://media/external/audio/media/0
    java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/audio/media/0
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1420)
        at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1101)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1073)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1001)
        at com.andrew.apollo.MusicPlaybackService$MultiPlayer.setDataSourceTask(MusicPlaybackService.java:2815)
        at com.andrew.apollo.MusicPlaybackService$MultiPlayer.lambda$yPg1J85y4QTySnOeeoNfUtKjA08(Unknown Source:0)
        at com.andrew.apollo.-$$Lambda$MusicPlaybackService$MultiPlayer$yPg1J85y4QTySnOeeoNfUtKjA08.run(Unknown Source:10)
        at com.frostwire.android.util.Asyncs.lambda$async$12(Asyncs.java:170)
        at com.frostwire.android.util.-$$Lambda$Asyncs$Wh-LQ-qC9-PkoHhdZXCRVHvxFgo.run(Unknown Source:2)
        at com.frostwire.android.util.Asyncs.lambda$invokeAsyncSupport$32(Asyncs.java:380)
        at com.frostwire.android.util.-$$Lambda$Asyncs$6mnyDfjODWzTGIRho6tr-HrdXZc.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by gubatron** [comment]
`java.lang.IllegalArgumentException: Invalid column audio._id AS _id`
