### ISSUE TITLE
Android App Crash

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#854]
App is Crashing with following crash log:
2019-12-27 21:50:24.020 22024-22024/com.frostwire.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frostwire.android, PID: 22024
    java.lang.RuntimeException: Too many tasks in the queue
        at com.frostwire.android.gui.services.EngineThreadPool.verifyTask(EngineThreadPool.java:73)
        at com.frostwire.android.gui.services.EngineThreadPool.execute(EngineThreadPool.java:29)
        at com.frostwire.android.util.Asyncs.invokeAsyncSupport(Asyncs.java:341)
        at com.frostwire.android.util.Asyncs.async(Asyncs.java:287)
        at com.frostwire.android.util.ImageLoader.load(ImageLoader.java:240)
        at com.frostwire.android.util.ImageLoader.load(ImageLoader.java:229)
        at com.frostwire.android.util.ImageLoader.load(ImageLoader.java:183)
        at com.andrew.apollo.cache.ImageWorker.loadImage(ImageWorker.java:67)
        at com.andrew.apollo.cache.ImageFetcher.loadArtistImage(ImageFetcher.java:38)
        at com.andrew.apollo.adapters.ArtistAdapter.getView(ArtistAdapter.java:36)
        at android.widget.AbsListView.obtainView(AbsListView.java:2454)
        at android.widget.GridView.makeAndAddView(GridView.java:1459)
        at android.widget.GridView.makeRow(GridView.java:384)
        at android.widget.GridView.fillDown(GridView.java:325)
        at android.widget.GridView.fillSpecific(GridView.java:606)
        at android.widget.GridView.layoutChildren(GridView.java:1314)
        at android.widget.AbsListView.onLayout(AbsListView.java:2249)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6259)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:21927)

**Comment by gubatron** [comment]
what build is this? are you running from source?

**Comment by fahimanwer** [comment]
Build is FrostWire Plus. The issue Appeared while I was clicking on next songs quickly.

**Comment by gubatron** [comment]
Thank you, I'll give it a try.

Do you remember if you were inside the Music Player screen, or where you on another screen or changed the songs from the android's notification area? or were you changing the songs using a device via bluetooth?

The more specific you can be the easier for me to try and replicate the issue

**Comment by fahimanwer** [comment]
I was in the music player section, and it occurs randomly. Means not every time I do the same thing crashes the app.

**Comment by gubatron** [comment]
I was able to replicate this crash.

This is an intentional crash which should only occur if you're running from the source code.

```
private void verifyTask(Object task) {
        if (Debug.hasContext(task)) {
            throw new RuntimeException("Runnable/task contains context, possible context leak");
        }

        if (Debug.isEnabled()) {
            taskStack.put(task, getStack());
        }

        // if debug/development, allow only 20 tasks in the queue
        if (Debug.isEnabled() && getQueue().size() > 20) {
            dumpTasks();
            throw new RuntimeException("Too many tasks in the queue");
        }
    }
```

regardless, I'm taking a look at the code that loads the album art to see if the art can be loaded only if you're actually playing the song, meaning, maybe more than 1/2 a second has passed, and not right away, this way you should be able to skip super fast a bunch of songs (more than 20) and not load the thread pool with useless tasks.

**Comment by gubatron** [comment]
Thanks for reporting this, it opened a whole can of worms as I try to make the app throttle submissions to the threadpool, there are other spots where it's submitting tasks that I think can be omitted if the user is skipping fast.

I'll link to the final patch.

Thanks @fahimanwer

**Comment by gubatron** [comment]
issue fixed, too many commits to link to. Thank you so much for reporting this, we now have throttled thread execution in many places
