### ISSUE TITLE
[android] Possible context leak at com.frostwire.android.gui.services.EngineBroadcastReceiver.handleDisconnectedNetwork(EngineBroadcastReceiver.java:99)

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#872]
E/AndroidRuntime: FATAL EXCEPTION: Engine-thread-idle
    Process: com.frostwire.android, PID: 21702
    java.lang.RuntimeException: Runnable/task contains context, possible context leak
        at com.frostwire.android.gui.services.EngineThreadPool.verifyTask(EngineThreadPool.java:69)
        at com.frostwire.android.gui.services.EngineThreadPool.execute(EngineThreadPool.java:33)
        at com.frostwire.android.util.Asyncs.invokeAsyncSupport(Asyncs.java:451)
        at com.frostwire.android.util.Asyncs.async(Asyncs.java:383)
        at com.frostwire.android.gui.services.EngineBroadcastReceiver.handleDisconnectedNetwork(EngineBroadcastReceiver.java:99)
        at com.frostwire.android.gui.services.EngineBroadcastReceiver.handleConnectivityChange(EngineBroadcastReceiver.java:74)
        at com.frostwire.android.gui.services.EngineBroadcastReceiver.lambda$HD10eFZaqmqvDyf0uz79WMXnXuU(Unknown Source:0)
        at com.frostwire.android.gui.services.-$$Lambda$EngineBroadcastReceiver$HD10eFZaqmqvDyf0uz79WMXnXuU.run(Unknown Source:6)
        at com.frostwire.android.util.Asyncs.lambda$async$10(Asyncs.java:138)
        at com.frostwire.android.util.-$$Lambda$Asyncs$CPYl0gOP3-ijEN8WosCUIHS1VUc.run(Unknown Source:2)
        at com.frostwire.android.util.Asyncs.lambda$invokeAsyncSupport$36(Asyncs.java:460)
        at com.frostwire.android.util.-$$Lambda$Asyncs$piUSnRIWAsQ6edqsYW7LBsUznK8.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by gubatron** [comment]
Awesome find!

**Comment by gubatron** [comment]
Looks like we're already on a background thread and fire another one thus the leak detector screams.

Gotta see in what other places than this
https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/gui/services/EngineBroadcastReceiver.java#L77

`handleConnectivityChange` is being called and make sure we don't needlessly call async further down in the stack.

**Comment by fahimanwer** [comment]
I got more crashes, I will add them in the issue section in a few hours.

**Comment by qyzhaojinxi** [comment]
how to fix this crash?

**Comment by gubatron** [comment]
gotta read what happens at `handleConnectivityChange` and why would a Context be leaked

**Comment by gubatron** [comment]
@copilot This is a very old bug I may have already fixed, if that's not the case, fix it.
