### ISSUE TITLE
[desktop] module java.desktop does not "opens javax.swing" to unnamed module

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#975]
jdk17 issue

```java
java.lang.reflect.InaccessibleObjectException: Unable to make field private javax.swing.JPopupMenu javax.swing.JMenu.popupMenu accessible: module java.desktop does not "opens javax.swing" to unnamed module @1e66f1f5
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.frostwire.gui.theme.SkinMenu.ensurePopupMenuCreated(SkinMenu.java:22)
        at com.frostwire.gui.theme.SkinMenu.<init>(SkinMenu.java:13)
        at com.limegroup.gnutella.gui.tables.ColumnSelectionMenu.createMoreOptions(ColumnSelectionMenu.java:99)
        at com.limegroup.gnutella.gui.tables.ColumnSelectionMenu.<init>(ColumnSelectionMenu.java:88)
        at com.limegroup.gnutella.gui.tables.AbstractTableMediator.createColumnSelectionMenu(AbstractTableMediator.java:658)
        at com.limegroup.gnutella.gui.tables.AbstractTableMediator.handleHeaderPopupMenu(AbstractTableMediator.java:726)
        at com.limegroup.gnutella.gui.tables.HeaderMouseListener.tryPopup(HeaderMouseListener.java:88)
        at com.limegroup.gnutella.gui.tables.HeaderMouseListener.mousePressed(HeaderMouseListener.java:39)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by gubatron** [comment]
fixed by https://github.com/frostwire/frostwire/commit/fbeda0a8d9d71380e6793904d6d808deed0314d5
