### ISSUE TITLE
[desktop] 6.2.2 - java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.picker_log_alert_priority_get()

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#99]
Getting a lot of these bug reports lately.

```
java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.picker_log_alert_priority_get()I
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.picker_log_alert_priority_get(Native Method)
        at com.frostwire.jlibtorrent.swig.picker_log_alert.<clinit>(Unknown Source)
        at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(Unknown Source)
        at com.frostwire.bittorrent.BTEngine.<clinit>(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.startBittorrentCore(Unknown Source)
        at com.limegroup.gnutella.gui.Initializer.initialize(Unknown Source)
        at com.limegroup.gnutella.gui.GUILoader.load(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.limegroup.gnutella.gui.Main.main(Unknown Source)
``
```

**Comment by aldenml** [comment]
Yes, I saw it, can't imagine how is that possible

**Comment by gubatron** [comment]
wonder if this is related to that priority bug that guy was reporting on jlibtorrent :)

**Comment by aldenml** [comment]
no related
